### ISSUE TITLE
error when sending url

### ISSUE THREAD

**Issue by theazran** [Gimenz/nganu#2]
error nganu => TypeError: Cannot read property 'logger' of undefined
at generateThumbnail (c:\botdl\node_modules\@adiwajshing\baileys-md\lib\Utils\messages-media.js:211:27)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async sendFileFromUrl (c:\botdl\index.js:341:29)
at async EventEmitter.<anonymous> (c:\botdl\index.js:249:29)

**Comment by Gimenz** [comment]
have you installed ffmpeg? generateThumbnail function are requires ffmpeg . here [extractVideoThumb ](https://github.com/adiwajshing/Baileys/blob/e3e521b3850979f3bf081082bc8a80a05694070c/src/WAConnection/Utils.ts#L234)
